platform :ios, '8.0'
use_frameworks!

source 'https://github.com/CocoaPods/Specs.git'

target 'TalntsNavigationControls' do

pod 'HamburgerMenu', :git => "https://github.com/TalntsApp/TalntsNavigationControls.git"
pod 'ActionMenu', :git => "https://github.com/TalntsApp/TalntsNavigationControls.git"
pod 'PageMenu', :git => "https://github.com/TalntsApp/TalntsNavigationControls.git"

end

